# Generated by Django 5.1.2 on 2024-10-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTempo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao_trabalho', models.TextField()),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tempo', to='tarefa.tarefa')),
            ],
        ),
    ]
